const projects = [
  {
    id: 7,
    name: "Abuelitos",
    year: 2024,
    month: "May",
    author: "Brandon Castillo",
    image: "/projects-img/yourelder/abuelitos-video.png",
    web: "https://yourelder.vercel.app/",
    youtube: "https://www.youtube.com/embed/C8Xrna8P8zE",
    video: "https://www.youtube.com/watch?v=C8Xrna8P8zE",
    github: "http://github.com/pibelanzallamas/yourelder",
    description: "Youtube song searcher for elders.",
    descripcion: "Buscador de Youtube más simplificado.",
    tags: ["react", "html", "youtube"],
  },
  {
    id: 6,
    name: "Carbon Copy",
    year: 2024,
    month: "May",
    author: "Brandon Castillo",
    image: "/projects-img/cc/carbon-copy-home.png",
    darkimage: "/projects-img/cc/carbon-copy-home.png",
    web: "http://carbon-copy-omega.vercel.app",
    youtube: "https://www.youtube.com/embed/UcbWm7Cd8Aw?si=ID007IVDWyYolxHZ",
    video: "https://www.youtube.com/watch?v=UcbWm7Cd8Aw",
    github: "https://github.com/pibelanzallamas/carbon-copy",
    description: "Application to edit and export code to PNG images.",
    descripcion: "Aplicación para editar y exportar código a imágenes PNG.",
    tags: [
      "react",
      "redux",
      "nodejs",
      "sass",

      "dotenv",
      "jwt",
      "javascript",
      "ace-react",
      "sequelize",
      "postgres",
    ],
  },
  {
    id: 5,
    name: "Dreamer Paintings",
    year: 2023,
    month: "nov",
    author: "Brandon Castillo",
    image: "/projects-img/dp/dreamer-paintings.png",
    darkimage: "/projects-img/dp/dreamer-paintings-dark.png",
    web: "https://dreamer-paintings.vercel.app",
    youtube: "https://www.youtube.com/embed/QorLsTcNgS0?si=cBHNnpnPMjbMQ9EP",
    video: "https://www.youtube.com/watch?v=QorLsTcNgS0",
    github: "https://github.com/pibelanzallamas/dreamers-paintings",
    description:
      "Exploratory and informative website showcasing the paintings of a talented friend from the city of Buenos Aires.",
    descripcion:
      "Sitio web explorador e informativo de las pinturas de un talentoso amigo, de la ciudad de Buenos Aires.",
    tags: ["react", "redux", "sass", "vite", "javascript", "html", "css"],
  },
  {
    id: 4,
    name: "House of Dev",
    year: 2023,
    month: "sep",
    author: "Brandon Castillo",
    image: "/projects-img/hod/house-of-dev-image.png",
    web: "https://house-of-dev-client.vercel.app",
    youtube: "https://www.youtube.com/embed/uYUc50qGQXY?si=7xFUkmvLsrWGAYIu",
    video: "https://www.youtube.com/watch?v=uYUc50qGQXY",
    github: "https://github.com/pibelanzallamas/house-of-dev-client-deploy",
    description:
      "Web application for searching properties with various filters, sorting options, favorites, scheduling appointments, email confirmation, and admin mode.",
    descripcion:
      "Aplicación web para buscar propiedades con diversos filtros, opciones de ordenamiento, favoritos, programación de citas, confirmación por correo electrónico y modo administrador.",
    tags: [
      "html",
      "css",
      "javascript",
      "nodejs",
      "express",
      "postgres",
      "sequelize",
      "jwt",
      "mui",
      "redux",
    ],
  },
  {
    id: 3,
    name: "My Movie Crib",
    year: 2023,
    month: "jul",
    author: "Brandon Castillo",
    image: "/projects-img/mmc/MMC-Home.png",
    web: "https://my-movie-crib-front.vercel.app/1",
    youtube: "https://player.vimeo.com/video/897978371?h=3227292034",
    video: "https://vimeo.com/897978371?share=copy",
    github: "https://github.com/pibelanzallamas/my-movie-crib-front",
    description:
      "Web application for searching movies, viewing the trending ones, saving favorites, and visiting their websites.",
    descripcion:
      "Aplicación web para buscar películas, ver las más populares, guardar favoritas y visitar sus sitios web.",
    tags: [
      "html",
      "css",
      "javascript",
      "nodejs",
      "express",
      "postgres",
      "sequelize",
      "bulma",
      "jwt",
    ],
  },
  // {
  //   id: 2,
  //   name: "Metalhead",
  //   year: 2023,
  //   month: "may",
  //   author: "Brandon Castillo",
  //   image: "/projects-img/metalhead/metalhead-image.png",
  //   web: "https://pibelanzallamas.github.io/metalhead",
  //   youtube: "https://www.youtube.com/embed/MixyinKSZhk?si=Oo-y5EnDjF4wcmSJ",
  //   video: "https://www.youtube.com/watch?v=MixyinKSZhk",
  //   github: "https://github.com/pibelanzallamas/metalhead",
  //   description:
  //     "Little project that includes a mixtape of ps1 videogames, breakcore music and live nineties bands.",
  //   descripcion:
  //     "Pequeño proyecto que incluye una mezcla de videojuegos de PS1, música breakcore y bandas de los noventa",
  //   tags: ["html", "css", "nodejs", "express", "postgres", "sql"],
  // },
  // {
  //   id: 1,
  //   name: "Sacrificial Suicide",
  //   year: 2023,
  //   month: "feb",
  //   author: "Brandon Castillo",
  //   image: "/projects-img/sacrificial suicide/sacrificial-suicide-image.png",
  //   web: "https://pibelanzallamas.github.io/sacrificialsuicide",
  //   youtube: "https://www.youtube.com/embed/5aZPzEy0ANc?si=A7DxxHmdLj-j5wnN",
  //   video: "https://www.youtube.com/watch?v=5aZPzEy0ANc",
  //   github: "https://github.com/pibelanzallamas/sacrificialsuicide",
  //   description: "Little project that counts your days alive.",
  //   descripcion: "Pequeño proyecto que te calcula los días vivo.",
  //   tags: ["html", "css", "nodejs", "express", "postgres", "sql"],
  // },
];

export default projects;
