const projects = [
  {
    id: 4,
    name: "House of Dev",
    year: 2023,
    month: "sep",
    author: "Brandon Castillo",
    image: "/projects-img/hod/house-of-dev-image.png",
    web: "https://house-of-dev-client.vercel.app",
    youtube: "https://youtu.be/uYUc50qGQXY?si=BwhmL5XcZbPBLH-n",
    github: "https://github.com/pibelanzallamas/house-of-dev-client-deploy",
    description:
      "Web application for searching properties with various filters, sorting options, favorites, scheduling appointments, email confirmation, and admin mode.",
    tags: ["html", "css", "nodejs", "express", "postgres", "sql"],
  },
  {
    id: 3,
    name: "My Movie Crib",
    year: 2023,
    month: "jul",
    author: "Brandon Castillo",
    image: "/projects-img/mmc/MMC-Home.png",
    web: "https://vimeo.com/897978371?share=copy",
    youtube: "https://youtu.be/vW33QvnaI-4?si=tIYkGQGtq5ENYtId",
    github: "https://github.com/pibelanzallamas/my-movie-crib-front",
    description: `Web application for searching movies, viewing the trending ones, saving favorites, and visiting their websites.`,
    tags: ["html", "css", "nodejs", "express", "postgres", "sql"],
  },
  {
    id: 2,
    name: "Metalhead",
    year: 2023,
    month: "may",
    author: "Brandon Castillo",
    image: "/projects-img/metalhead/metalhead-image.png",
    web: "https://pibelanzallamas.github.io/metalhead",
    youtube: "https://youtu.be/MixyinKSZhk?si=byWUN4vjyQc56Kp0",
    github: "https://github.com/pibelanzallamas/metalhead",
    description: `Little project that includes a mixtape of ps1 videogames, breakcore music and live 90s bands.`,
    tags: ["html", "css", "nodejs", "express", "postgres", "sql"],
  },
  {
    id: 1,
    name: "Sacrificial Suicide",
    year: 2023,
    month: "feb",
    author: "Brandon Castillo",
    image: "/projects-img/sacrificial suicide/sacrificial-suicide-image.png",
    web: "https://pibelanzallamas.github.io/sacrificialsuicide",
    youtube: "https://youtu.be/gLCG9v28dcs?si=u1lagDbo6xjIlI6-",
    github: "https://github.com/pibelanzallamas/sacrificialsuicide",
    description: `Little project that counts your days in this earth.`,
    tags: ["html", "css", "nodejs", "express", "postgres", "sql"],
  },
];

export default projects;
