const projects = [
  {
    id: 4,
    name: "House of Dev",
    year: 2023,
    month: "sep",
    author: "Brandon Castillo",
    image: "/projects-img/hod/house-of-dev-image.png",
    web: "https://house-of-dev-client.vercel.app",
    youtube: "",
    github: "https://github.com/pibelanzallamas/house-of-dev-client-deploy",
    // description: `Web application designed with the help of SASS and Figma. Functionalities implemented using React, Redux, and Axios. It includes features for searching properties by neighborhood, city, country, rooms, availability, categories (PH, House, etc), and also sorting them by price or publication date. Users can save favorites, write reviews, and schedule appointments. In admin mode, you can modify everything, including users, properties, appointments, and reviews.`,
    description:
      "Website with several filters, saved of properties, appointment schedule, admin mode and more.",
    tags: ["html", "css", "nodejs", "express", "postgres", "sql"],
  },
  {
    id: 3,
    name: "My Movie Crib",
    year: 2023,
    month: "jul",
    author: "Brandon Castillo",
    image: "/projects-img/mmc/MMC-Home.png",
    web: "https://my-movie-crib-front.vercel.app",
    youtube: "",
    github: "https://github.com/pibelanzallamas/my-movie-crib-front",
    description: `Web application for searching movies, viewing the trending ones, saving favorites, and visiting their websites.`,
    tags: ["html", "css", "nodejs", "express", "postgres", "sql"],
  },
  {
    id: 2,
    name: "Metalhead",
    year: 2023,
    month: "may",
    author: "Brandon Castillo",
    image: "/projects-img/metalhead/metalhead-image.png",
    web: "https://pibelanzallamas.github.io/metalhead",
    youtube: "",
    github: "https://github.com/pibelanzallamas/metalhead",
    description: `Personal project of mine, that includes a mixtape of ps1 videogames, breakcore music and 90s bands.`,
    tags: ["html", "css", "nodejs", "express", "postgres", "sql"],
  },
  {
    id: 1,
    name: "Sacrificial Suicide",
    year: 2023,
    month: "feb",
    author: "Brandon Castillo",
    image: "/projects-img/sacrificial suicide/sacrificial-suicide-image.png",
    web: "https://pibelanzallamas.github.io/sacrificialsuicide",
    youtube: "",
    github: "https://github.com/pibelanzallamas/sacrificialsuicide",
    description: `Little project that counts your days in this earth.`,
    tags: ["html", "css", "nodejs", "express", "postgres", "sql"],
  },
];

export default projects;
