const projects = [
   {
    id: 12,
    name: "CGC minc",
    year: 2025,
    month: "DIC",
    author: "Brandon Castillo",
    image:
      "https://res.cloudinary.com/daynclfo8/image/upload/v1767315491/2026-01-01-21-57-29_c8rsci.png",
    web: "https://cgcminc.vercel.app/",
    youtube: "d9R3duNF7eg",
    video: "https://www.youtube.com/watch?v=d9R3duNF7eg",
    github: "https://github.com/pibelanzallamas/minc.cg/",
    description:
      "Website created for the company CGC minc, focused on building community and a marketplace for clothing and accessories. [in development]",
    descripcion:
      "Sitio web realizado para la compañia CGC minc, enfocada en crear comunidad y un marketplace de indumentaria y accesorios. [en desarrollo]",
    tags: ["react", "redux", "sass", "axios", "figma", "javascript"],
  },
    {
    id: 11,
    name: "Brandon Castillo Web",
    year: 2025,
    month: "Mar",
    author: "Brandon Castillo",
    image:
      "https://res.cloudinary.com/daynclfo8/image/upload/v1767358568/2026-01-02-09-55-52_elwszo.png",
    web: "https://brandon-castillo.vercel.app/",
    youtube: "fQGRjpaZeFk",
    video: "https://www.youtube.com/watch?v=fQGRjpaZeFk",
    github: "http://github.com/pibelanzallamas/brandon-castillo",
    description:
      "My personal website where I share my experience, education, and professional background.",
    descripcion:
      "Mi sitio personal donde hablo sobre mi experiencia, mi educación y sobre mi trayectoria.",
    tags: ["react", "redux", "sass", "axios", "figma", "javascript"],
  },
    {
    id: 7,
    name: "YouFast",
    year: 2024,
    month: "May",
    author: "Brandon Castillo",
    image:
      "https://res.cloudinary.com/daynclfo8/image/upload/v1768158039/2026-01-11-15-57-10_wgtj9p.png",
    web: "https://youfast.vercel.app/",
    youtube: "IoIIYAMlT6g",
    video: "https://www.youtube.com/watch?v=IoIIYAMlT6g",
    github: "http://github.com/pibelanzallamas/youfast",
    description: "Song search app for grandparents: type the song, artist, press Enter, and the song starts playing instantly.⚡",
    descripcion: "Buscador de canciones para abuelos y abuelas, escribis cancion, artista, presionas enter y ya suena la cancion.⚡",
    tags: ["react", "redux", "sass", "html/css", "dotenv"],
  },

    {
    id: 8,
    name: "Your Mood",
    year: 2024,
    month: "Jul",
    author: "Brandon Castillo",
    image:
      "https://res.cloudinary.com/daynclfo8/image/upload/v1768150121/2026-01-11-13-48-29_zktvzz.png",
    web: "https://your-mood.vercel.app/",
    youtube: "2PzNBIX46Wc",
    video: "https://www.youtube.com/watch?v=2PzNBIX46Wc",
    github: "http://github.com/pibelanzallamas/your-mood",
    description: "Website that recomends random songs based on your mood.",
    descripcion: "Sitio que recomienda canciones según tu estado de animo.",
    tags: ["react", "sass", "axios", "html/css", "javascript"],
  },
  {
    id: 6,
    name: "Carbon Copy",
    year: 2024,
    month: "May",
    author: "Brandon Castillo",
    image:  "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1732569610/carbon2.png",
    web: "http://carbon-copy-omega.vercel.app",
    youtube: "bb8RomFHFdg",
    video: "https://www.youtube.com/watch?v=bb8RomFHFdg",
    github: "https://github.com/pibelanzallamas/carbon-copy",
    description: "Web application to format and export code snippets from different languages to PNG format.",
    descripcion: "Aplicación web para formatear y exportar fragmentos de código de diferentes lenguajes a formato PNG.",
    tags: [
      "nodejs",
      "express",
      "postgres",
      "sequelize",
      "jwt",
      "dotenv",
      "figma",
      "react",
      "redux",
      "ace-react",
      "mui",
      "sass",
    ],
  },
    {
    id: 4,
    name: "House of Dev",
    year: 2023,
    month: "sep",
    author: "Brandon Castillo",
    image:
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1732568386/house.png",
    web: "https://house-of-dev-client.vercel.app",
    youtube: "LiaV7xHjJmk",
    video: "https://www.youtube.com/watch?v=LiaV7xHjJmk",
    github: "https://github.com/pibelanzallamas/house-of-dev-client-deploy",
    description:
      "A web application similar to a real estate website, with various filters, sorting, appointment scheduling, favorites, email confirmation, admin mode, and more.",
    descripcion:
      "Aplicación web simil a sitio inmobiliario, con diversos filtros, ordenamientos, programación de citas, favoritos, confirmación por mail, modo administrador y más.",
    tags: [
      "nodejs",
      "express",
      "postgres",
      "sequelize",
      "jwt",
      "figma",
      "react",
      "redux",
      "mui",
      "sass",
    ],
  },


  {
    id: 10,
    name: "Calles Construction",
    year: 2025,
    month: "Feb",
    author: "Brandon Castillo",
    image:
      "https://res.cloudinary.com/daynclfo8/image/upload/v1767358479/2026-01-02-09-54-11_cz8zaq.png",
    web: "https://calles-construction.vercel.app/",
    youtube: "mOV8O6jPwC4",
    video: "https://www.youtube.com/watch?v=mOV8O6jPwC4",
    github: "http://github.com/pibelanzallamas/calles-construction",
    description:
      "Website built for construction company located in New York City.",
    descripcion:
      "Sitio web realizado para empresa de construcción ubicada en la ciudad de Nueva York.",
    tags: [
        "nodejs",
        "express",
        "postgres",
        "sequelize",
        "jwt",
        "dotenv",
        "miro",
        "react",
        "redux",
        "mui",
        "sass",
    ],
  },

  {
    id: 5,
    name: "Dreamer Paintings",
    year: 2024,
    month: "Apr",
    author: "Brandon Castillo",
    image:
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1740082053/Captura_de_Pantalla_2025-02-20_a_la_s_17.06.43_vg9yro.png",
    darkimage: "/projects-img/dp/dreamer-paintings-dark.png",
    web: "https://dreamer-paintings.vercel.app",
    youtube: "ihcTIHnBINU",
    video: "https://www.youtube.com/watch?v=ihcTIHnBINU",
    github: "https://github.com/pibelanzallamas/dreamers-paintings",
    description:
      "Web site made for abstract painting artist from the city of Buenos Aires.",
    descripcion:
      "Sitio web hecho para artista de pinturas abstractas desde la ciudad de Buenos Aires.",
    tags: ["react", "redux", "sass", "javascript"],
  },

  {
    id: 9,
    name: "Yu-Gi-Oh! Randomizer!",
    year: 2024,
    month: "Jul",
    author: "Brandon Castillo",
    image:
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1732663508/yugi.png",
    web: "https://givemeayugiohcard.vercel.app/",
    youtube: "NEzQ7VnWCLI",
    video: "https://www.youtube.com/watch?v=NEzQ7VnWCLI",
    github: "http://github.com/pibelanzallamas/givemeayugiohcard",
    description: "Get a random Yu-Gi-Oh! card.",
    descripcion: "Obtené una carta aleatoria de Yu-Gi-Oh!.",
    tags: ["react", "sass", "axios", "html/css", "javascript"],
  },
  {
    id: 3,
    name: "My Movie Crib",
    year: 2023,
    month: "jul",
    author: "Brandon Castillo",
    image:
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1732567910/crib.png",
    web: "https://my-movie-crib.vercel.app/1",
    youtube: "j-qgyoaeJN4",
    video: "https://www.youtube.com/watch?v=j-qgyoaeJN4",
    github: "https://github.com/pibelanzallamas/my-movie-crib-front",
    description:
      "Web application for searching movies, viewing the trending ones, saving favorites, and visiting their websites.",
    descripcion:
      "Aplicación web para buscar películas, ver populares, guardar favoritos y más",
    tags: [
      "nodejs",
      "express",
      "postgres",
      "sequelize",
      "jwt",
      "react",
      "redux",
      "bulma",
    ],
  },
  {
    id: 2,
    name: "Metalhead",
    year: 2023,
    month: "may",
    author: "Brandon Castillo",
    image:
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1732841668/metal.png",
    web: "https://metalhead.vercel.app",
    youtube: "pN2r5AhwKrU",
    video: "https://www.youtube.com/watch?v=pN2r5AhwKrU",
    github: "https://metalhead.vercel.app",
    description:
      "Little project that includes a mixtape of videogames, music and live bands.",
    descripcion:
      "Pequeño proyecto que incluye una mezcla de videojuegos, música, y bandas en vivo",
    tags: ["html/css", "javascript"]
  },
  {
    id: 1,
    name: "Sacrificial Suicide",
    year: 2023,
    month: "feb",
    author: "Brandon Castillo",
    image:
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1732841819/sacri.png",
    web: "https://pibelanzallamas.github.io/sacrificial-suicide/",
    youtube: "g7rukS6FLNQ",
    video: "https://www.youtube.com/watch?v=g7rukS6FLNQ",
    github: "https://sacrificial-suicide.vercel.app",
    description: "Earth days counter.",
    descripcion: "Contador de dias en la tierra.",
    tags: ["html/css", "javascript"],
  },
];

export default projects;
