const projects = [
  {
    id: 11,
    name: "Brandon Castillo Web",
    year: 2025,
    month: "Feb",
    author: "Brandon Castillo",
    image:
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1754251248/2025-08-03_17-00_hns8sk.png",
    web: "https://brandon-castillo.vercel.app/",
    youtube: "wb4fpWTEs9M",
    video: "https://www.youtube.com/watch?v=wb4fpWTEs9M",
    github: "http://github.com/pibelanzallamas/brandon-castillo",
    description:
      "My own personal website, where I talk about myself, my experience, and update my latest videos.",
    descripcion:
      "Mi sitio personal, donde hablo acerca de mi, mi experiencia y subo mis últimos videos.",
    tags: ["react", "vite", "sass", "axios", "javascript"],
  },
  {
    id: 10,
    name: "Calles Construction",
    year: 2024,
    month: "Sep",
    author: "Brandon Castillo",
    image:
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1732610191/calles.png",
    web: "https://calles-construction.vercel.app/",
    youtube: "mOV8O6jPwC4",
    video: "https://www.youtube.com/watch?v=mOV8O6jPwC4",
    github: "http://github.com/pibelanzallamas/calles-construction",
    description:
      "Web site to showcase Calle's Construction different works, from drywall, to electricity, allows to upload jobs with details and images.",
    descripcion:
      "Sitio web explorador e informativo de los trabajos realizados por la empresa de construccion Calle's Construction ubicada en New Jersey, permite agregar trabajos con detalle e imagenes.",
    tags: ["react", "vite", "sass", "axios", "javascript"],
  },
  {
    id: 9,
    name: "Yu-Gi-Oh! Randomizer!",
    year: 2024,
    month: "Jul",
    author: "Brandon Castillo",
    image:
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1732663508/yugi.png",
    web: "https://givemeayugiohcard.vercel.app/",
    youtube: "NEzQ7VnWCLI",
    video: "https://www.youtube.com/watch?v=NEzQ7VnWCLI",
    github: "http://github.com/pibelanzallamas/givemeayugiohcard",
    description: "Get a Yu-Gi-Oh! card.",
    descripcion: "Obtene un carta Yu-Gi-Oh!",
    tags: ["react", "vite", "sass", "axios", "javascript"],
  },
  {
    id: 8,
    name: "Your Mood",
    year: 2024,
    month: "Jul",
    author: "Brandon Castillo",
    image:
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1749922322/2025-06-14_14-31_hxnue7.png",
    web: "https://your-mood.vercel.app/",
    youtube: "AoEKSxLDWao",
    video: "https://www.youtube.com/watch?v=AoEKSxLDWao",
    github: "http://github.com/pibelanzallamas/your-mood",
    description: "Website for recommending music based on your mood.",
    descripcion: "Sitio web que te recomienda musica segun tu estado de animo.",
    tags: ["react", "vite", "sass", "axios", "javascript"],
  },
  {
    id: 7,
    name: "YouFast",
    year: 2024,
    month: "May",
    author: "Brandon Castillo",
    image:
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1749922540/2025-06-14_14-35_yit3uy.png",
    web: "https://youfast.vercel.app/",
    youtube: "lVOHTdXnGaI",
    video: "https://www.youtube.com/watch?v=lVOHTdXnGaI",
    github: "http://github.com/pibelanzallamas/youfast",
    description: "Youtube song searcher for elders.",
    descripcion: "Buscador de Youtube más simplificado.",
    tags: ["react", "html", "youtube"],
  },
  {
    id: 6,
    name: "Carbon Copy",
    year: 2024,
    month: "May",
    author: "Brandon Castillo",
    image:  "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1732569610/carbon2.png",
    web: "http://carbon-copy-omega.vercel.app",
    youtube: "bb8RomFHFdg",
    video: "https://www.youtube.com/watch?v=bb8RomFHFdg",
    github: "https://github.com/pibelanzallamas/carbon-copy",
    description: "Application to edit and export code to PNG images.",
    descripcion: "Aplicación para editar y exportar código a imágenes PNG.",
    tags: [
      "react",
      "redux",
      "nodejs",
      "sass",
      "dotenv",
      "jwt",
      "javascript",
      "ace-react",
      "sequelize",
      "postgres",
    ],
  },
  {
    id: 5,
    name: "Dreamer Paintings",
    year: 2023,
    month: "nov",
    author: "Brandon Castillo",
    image:
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1740082053/Captura_de_Pantalla_2025-02-20_a_la_s_17.06.43_vg9yro.png",
    darkimage: "/projects-img/dp/dreamer-paintings-dark.png",
    web: "https://dreamer-paintings.vercel.app",
    youtube: "onv0uQ7Y_1I",
    video: "https://www.youtube.com/watch?v=onv0uQ7Y_1I",
    github: "https://github.com/pibelanzallamas/dreamers-paintings",
    description:
      "Exploratory and informative website showcasing the paintings of a talented friend from the city of Buenos Aires.",
    descripcion:
      "Sitio web explorador e informativo de las pinturas de un talentoso amigo, de la ciudad de Buenos Aires.",
    tags: ["react", "redux", "sass", "vite", "javascript", "html", "css"],
  },
  {
    id: 4,
    name: "House of Dev",
    year: 2023,
    month: "sep",
    author: "Brandon Castillo",
    image:
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1732568386/house.png",
    web: "https://house-of-dev-client.vercel.app",
    youtube: "LiaV7xHjJmk",
    video: "https://www.youtube.com/watch?v=LiaV7xHjJmk",
    github: "https://github.com/pibelanzallamas/house-of-dev-client-deploy",
    description:
      "Web application for searching properties with various filters, sorting options, favorites, scheduling appointments, email confirmation, and admin mode.",
    descripcion:
      "Aplicación web para buscar propiedades con diversos filtros, opciones de ordenamiento, favoritos, programación de citas, confirmación por correo electrónico y modo administrador.",
    tags: [
      "html",
      "css",
      "javascript",
      "nodejs",
      "express",
      "postgres",
      "sequelize",
      "jwt",
      "mui",
      "redux",
    ],
  },
  {
    id: 3,
    name: "My Movie Crib",
    year: 2023,
    month: "jul",
    author: "Brandon Castillo",
    image:
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1732567910/crib.png",
    web: "https://my-movie-crib-front.vercel.app/1",
    youtube: "j-qgyoaeJN4",
    video: "https://www.youtube.com/watch?v=j-qgyoaeJN4",
    github: "https://github.com/pibelanzallamas/my-movie-crib-front",
    description:
      "Web application for searching movies, viewing the trending ones, saving favorites, and visiting their websites.",
    descripcion:
      "Aplicación web para buscar películas, ver las más populares, guardar favoritas y visitar sus sitios web.",
    tags: [
      "html",
      "css",
      "javascript",
      "nodejs",
      "express",
      "postgres",
      "sequelize",
      "bulma",
      "jwt",
    ],
  },
  {
    id: 2,
    name: "Metalhead",
    year: 2023,
    month: "may",
    author: "Brandon Castillo",
    image:
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1732841668/metal.png",
    web: "https://pibelanzallamas.github.io/metalhead",
    youtube: "pN2r5AhwKrU",
    video: "https://www.youtube.com/watch?v=pN2r5AhwKrU",
    github: "https://github.com/pibelanzallamas/metalhead",
    description:
      "Little project that includes a mixtape of ps1 videogames, breakcore music and live nineties bands.",
    descripcion:
      "Pequeño proyecto que incluye una mezcla de videojuegos de PS1, música breakcore y bandas de los noventa",
    tags: ["html", "css", "nodejs", "express", "postgres", "sql"],
  },
  {
    id: 1,
    name: "Sacrificial Suicide",
    year: 2023,
    month: "feb",
    author: "Brandon Castillo",
    image:
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1732841819/sacri.png",
    web: "https://pibelanzallamas.github.io/sacrificial-suicide/",
    youtube: "g7rukS6FLNQ",
    video: "https://www.youtube.com/watch?v=g7rukS6FLNQ",
    github: "https://github.com/pibelanzallamas/sacrificialsuicide",
    description: "Little project that counts your days alive.",
    descripcion: "Pequeño proyecto que te calcula los días vivo.",
    tags: ["html", "css", "nodejs", "express", "postgres", "sql"],
  },
];

export default projects;
