const projects = [
  {
    id: 10,
    name: "Calles Construction",
    year: 2024,
    month: "Sep",
    author: "Brandon Castillo",
    image:
      "https://cvws.icloud-content.com/B/AYuj8IWgFEohS9YAM3qlM4Uszb2rAWfBcKQhg_IKIJw8JiKVNd_sBsUB/cc-home.png?o=AsPYvWDkygDhkaIMjPwzfMClRZkgF4cq_Si4bQpc5vi3&v=1&x=3&a=CAoggXc0azlYYzBHykDHRGPjlcU08qxWUtEVJLBaIaMN13wSbRCXk9LKrDIYl_CtzKwyIgEAUgQszb2rWgTsBsUBaiY41ZV8gx1-uSSABIOZBfI-7tiQBXrSFxRxwlxlpp8g-KpCDla1-XImBV8X_DGgy_Y15jA_HH5KX-RwxUH9ZydeZId5wor8em3WynSk0yA&e=1729958213&fl=&r=ed3b435d-dab4-43ce-b57f-be9fd7bf353c-1&k=FkdpAJnxjMSayZ2ClVzrNA&ckc=com.apple.clouddocs&ckz=com.apple.CloudDocs&p=156&s=jxdPfZ2cPqLTtAXYsWDrHgHWAAQ&cd=i",
    web: "https://calles-construction.vercel.app/",
    youtube: "https://www.youtube.com/embed/tPLa2s6PF-E",
    video: "https://www.youtube.com/watch?v=tPLa2s6PF-E",
    github: "http://github.com/pibelanzallamas/calles-construction",
    description:
      "Web site to showcase Calle's Construction different works, from drywall, to electricity, allows to upload jobs with details and images.",
    descripcion:
      "Sitio web explorador e informativo de los trabajos realizados por la empresa de construccion Calle's Construction ubicada en New Jersey, permite agregar trabajos con detalle e imagenes.",
    tags: ["react", "vite", "sass", "axios", "javascript"],
  },
  {
    id: 9,
    name: "Future Music Bot",
    year: 2024,
    month: "Jul",
    author: "Brandon Castillo",
    image: "/src//assets/future.png",
    web: "https://calles-construction.vercel.app/",
    youtube: "https://www.youtube.com/embed/tPLa2s6PF-E",
    video: "https://www.youtube.com/watch?v=tPLa2s6PF-E",
    github: "http://github.com/pibelanzallamas/calles-construction",
    description:
      "Web site to showcase Calle's Construction different works, from drywall, to electricity, allows to upload jobs with details and images.",
    descripcion:
      "Sitio web explorador e informativo de los trabajos realizados por la empresa de construccion Calle's Construction ubicada en New Jersey, permite agregar trabajos con detalle e imagenes.",
    tags: ["react", "vite", "sass", "axios", "javascript"],
  },
  {
    id: 8,
    name: "Yu-Gi-Oh! Randomizer!",
    year: 2024,
    month: "Jul",
    author: "Brandon Castillo",
    image: "",
    web: "https://givemeayugiohcard.vercel.app/",
    youtube: "https://www.youtube.com/embed/YhxYqo5ZVUI",
    video: "https://www.youtube.com/watch?v=YhxYqo5ZVUI",
    github: "http://github.com/pibelanzallamas/givemeayugiohcard",
    description: "Get a Yu-Gi-Oh! card.",
    descripcion: "Obtene un carta Yu-Gi-Oh!",
    tags: ["react", "vite", "sass", "axios", "javascript"],
  },
  {
    id: 7,
    name: "Abuelitos",
    year: 2024,
    month: "May",
    author: "Brandon Castillo",
    image:
      "https://cvws.icloud-content.com/B/AWxob9Lfa8v-Uup0faDDCMucuBUuAQst074-_O3TD9IaBmSmQ8i9G5C0/abuelitos.png?o=Aooe9aM07Z08nQ2cP7Zuq59VY0cuPaHynKi2Ahec54iS&v=1&x=3&a=CAogxt_0ipMgWFklZYRBxaFXiVzZ14nFAk3LuRMBC1iPKDESbRDa0KHPrDIY2q390KwyIgEAUgScuBUuWgS9G5C0aiaW6WqE1GiJtUvTtSi0mHAdGGxEj_PtJuizdtOwDAK4G_lHkG-CeHImtM0Xa1MbvKpJpFVhaUC2gHt2fu-UNGI0G--Wbfe61ExeMOA7Eak&e=1729967904&fl=&r=49ed4576-03b0-4896-8f58-312fdf7bb4fd-1&k=rqS40HrjlrG38qvuPlmroA&ckc=com.apple.clouddocs&ckz=com.apple.CloudDocs&p=156&s=k8BsCuRprK_18zRXE6KxeFOXXtk&cd=i",
    web: "https://yourelder.vercel.app/",
    youtube: "https://www.youtube.com/embed/C8Xrna8P8zE",
    video: "https://www.youtube.com/watch?v=C8Xrna8P8zE",
    github: "http://github.com/pibelanzallamas/yourelder",
    description: "Youtube song searcher for elders.",
    descripcion: "Buscador de Youtube más simplificado.",
    tags: ["react", "html", "youtube"],
  },
  {
    id: 6,
    name: "Carbon Copy",
    year: 2024,
    month: "May",
    author: "Brandon Castillo",
    image: "/src/assets/carbon.png",
    web: "http://carbon-copy-omega.vercel.app",
    youtube: "https://www.youtube.com/embed/UcbWm7Cd8Aw?si=ID007IVDWyYolxHZ",
    video: "https://www.youtube.com/watch?v=UcbWm7Cd8Aw",
    github: "https://github.com/pibelanzallamas/carbon-copy",
    description: "Application to edit and export code to PNG images.",
    descripcion: "Aplicación para editar y exportar código a imágenes PNG.",
    tags: [
      "react",
      "redux",
      "nodejs",
      "sass",
      "dotenv",
      "jwt",
      "javascript",
      "ace-react",
      "sequelize",
      "postgres",
    ],
  },
  {
    id: 5,
    name: "Dreamer Paintings",
    year: 2023,
    month: "nov",
    author: "Brandon Castillo",
    image:
      "https://cvws.icloud-content.com/B/ATQ8pxVhW1nn-Mi7OTM-xO893FUnAXhlULlsFHhtfOoDX3kUW3ON4c6W/dreamer.png?o=AtS4NAFweSsY-RkF59qK-KU5AFMeSl_otvL_VqC31uJr&v=1&x=3&a=CAogrOBMACzestzXukFbtp_NHGhTajofy0lATiO1MJvk1EISbRDM8azNrDIYzM6Iz6wyIgEAUgQ93FUnWgSN4c6WaiY9o7OPhD34_SM1jnkn4D-WxDzX0mkZN8Rr3OoNzuPeQlnguwpx_HIm8m2p4y0L-3evUjjnJfVrPYxKVpnOcYCsBUwXSq6TjwDAS_-mrhc&e=1729963894&fl=&r=0d6d5924-9eaa-417c-bad2-d7c02a842954-1&k=ayb4V-XOOVWSBLiYTEEsSg&ckc=com.apple.clouddocs&ckz=com.apple.CloudDocs&p=156&s=lL9jDkzmLTR-1KsnERwILlNKN6g&cd=i",
    darkimage: "/projects-img/dp/dreamer-paintings-dark.png",
    web: "https://dreamer-paintings.vercel.app",
    youtube: "https://www.youtube.com/embed/QorLsTcNgS0?si=cBHNnpnPMjbMQ9EP",
    video: "https://www.youtube.com/watch?v=QorLsTcNgS0",
    github: "https://github.com/pibelanzallamas/dreamers-paintings",
    description:
      "Exploratory and informative website showcasing the paintings of a talented friend from the city of Buenos Aires.",
    descripcion:
      "Sitio web explorador e informativo de las pinturas de un talentoso amigo, de la ciudad de Buenos Aires.",
    tags: ["react", "redux", "sass", "vite", "javascript", "html", "css"],
  },
  {
    id: 4,
    name: "House of Dev",
    year: 2023,
    month: "sep",
    author: "Brandon Castillo",
    image: "/src/assets/hod.png",
    web: "https://house-of-dev-client.vercel.app",
    youtube: "https://www.youtube.com/embed/uYUc50qGQXY?si=7xFUkmvLsrWGAYIu",
    video: "https://www.youtube.com/watch?v=uYUc50qGQXY",
    github: "https://github.com/pibelanzallamas/house-of-dev-client-deploy",
    description:
      "Web application for searching properties with various filters, sorting options, favorites, scheduling appointments, email confirmation, and admin mode.",
    descripcion:
      "Aplicación web para buscar propiedades con diversos filtros, opciones de ordenamiento, favoritos, programación de citas, confirmación por correo electrónico y modo administrador.",
    tags: [
      "html",
      "css",
      "javascript",
      "nodejs",
      "express",
      "postgres",
      "sequelize",
      "jwt",
      "mui",
      "redux",
    ],
  },
  {
    id: 3,
    name: "My Movie Crib",
    year: 2023,
    month: "jul",
    author: "Brandon Castillo",
    image: "",
    web: "https://my-movie-crib-front.vercel.app/1",
    youtube: "https://player.vimeo.com/video/897978371?h=3227292034",
    video: "https://vimeo.com/897978371?share=copy",
    github: "https://github.com/pibelanzallamas/my-movie-crib-front",
    description:
      "Web application for searching movies, viewing the trending ones, saving favorites, and visiting their websites.",
    descripcion:
      "Aplicación web para buscar películas, ver las más populares, guardar favoritas y visitar sus sitios web.",
    tags: [
      "html",
      "css",
      "javascript",
      "nodejs",
      "express",
      "postgres",
      "sequelize",
      "bulma",
      "jwt",
    ],
  },
  {
    id: 2,
    name: "Metalhead",
    year: 2023,
    month: "may",
    author: "Brandon Castillo",
    image:
      "https://cvws.icloud-content.com/B/AQ7eZoWO1d2qQET-APtC3qI0r1sSAfCPG59MCQa0eFXXKx6g8nVdvmwy/metalhead.png?o=ArhHJgugGvbNzUggOzgErvLpcMzknrYyS9dSyrGTCz53&v=1&x=3&a=CAog5XMGSXYN8zjMGfC4dBZFTDqZRJAxocJRD3T_8rgFH4oSbRCI-fzLrDIYiNbYzawyIgEAUgQ0r1sSWgRdvmwyaibCw5p4kpDOgAVZ3qkSrD8UCfwh3dZ4fIeCbp2BcG68Liii02-XMHImfMdOz8JNAWbR-sG9-yvzpQoHBKsrnzsHhfIDNxLfSGNhV6HMJwY&e=1729961011&fl=&r=24328f5a-099a-4c62-9a1c-9dd2b6f1d6b9-1&k=Iwxm9IeiLQm60Fbv_KCy3g&ckc=com.apple.clouddocs&ckz=com.apple.CloudDocs&p=156&s=0HBY-uI-ip3srfk0rv1tTNyF7cI&cd=i",
    web: "https://pibelanzallamas.github.io/metalhead",
    youtube: "https://www.youtube.com/embed/MixyinKSZhk?si=Oo-y5EnDjF4wcmSJ",
    video: "https://www.youtube.com/watch?v=MixyinKSZhk",
    github: "https://github.com/pibelanzallamas/metalhead",
    description:
      "Little project that includes a mixtape of ps1 videogames, breakcore music and live nineties bands.",
    descripcion:
      "Pequeño proyecto que incluye una mezcla de videojuegos de PS1, música breakcore y bandas de los noventa",
    tags: ["html", "css", "nodejs", "express", "postgres", "sql"],
  },
  {
    id: 1,
    name: "Sacrificial Suicide",
    year: 2023,
    month: "feb",
    author: "Brandon Castillo",
    image:
      "https://cvws.icloud-content.com/B/AYOmIFWQE7FQmbIvn3VtIa0vh6mbASUpX5HrJf14yrAnbGebWi2S2cJh/sacrificial.png?o=Ak8fiIl3ONzk6VVAhNnkcSk4fUM0VvkCu_EfEGSYIIGD&v=1&x=3&a=CAogGCA1bEK99tBT0ouZy1pmcoTXgHt2_rA1MvHq021iOBUSbRDYnr3NrDIY2PuYz6wyIgEAUgQvh6mbWgSS2cJhaibPF8BHju7tyX5bOzLdxsHekD_91E9HWntw-rcXpBiPA4_FDnEBOnImQvlA2WUA84QCN_tqMMrkoCMH8eu0LFgc7EcZUubLF6P5yPOEYXw&e=1729964162&fl=&r=6e6b56e3-a402-4520-82bc-a3a361ec7c7d-1&k=ETnJq0C-jYgTOeuKN4cZJg&ckc=com.apple.clouddocs&ckz=com.apple.CloudDocs&p=156&s=PCmT75iqmoR4SO_uW6Qy5stegUY&cd=i",
    web: "https://pibelanzallamas.github.io/sacrificial-suicide/",
    youtube: "https://www.youtube.com/embed/5aZPzEy0ANc?si=A7DxxHmdLj-j5wnN",
    video: "https://www.youtube.com/watch?v=5aZPzEy0ANc",
    github: "https://github.com/pibelanzallamas/sacrificialsuicide",
    description: "Little project that counts your days alive.",
    descripcion: "Pequeño proyecto que te calcula los días vivo.",
    tags: ["html", "css", "nodejs", "express", "postgres", "sql"],
  },
];

export default projects;
